rosewater: &rosewater "#f2d5cf"
flamingo: &flamingo "#eebebe"
pink: &pink "#f4b8e4"
mauve: &mauve "#ca9ee6"
red: &red "#e78284"
maroon: &maroon "#ea999c"
peach: &peach "#ef9f76"
yellow: &yellow "#e5c890"
green: &green "#a6d189"
teal: &teal "#81c8be"
sky: &sky "#99d1db"
sapphire: &sapphire "#85c1dc"
blue: &blue "#8caaee"
lavender: &lavender "#babbf1"
text: &text "#c6d0f5"
subtext1: &subtext1 "#b5bfe2"
subtext0: &subtext0 "#a5adce"
overlay2: &overlay2 "#949cbb"
overlay1: &overlay1 "#838ba7"
surface0: &surface0 "#3b414d"
base: &base "#303446"
mantle: &mantle "#292c3c"
crust: &crust "#2e3440"
dark_purple: &dark_purple "#6c77bb"
light_purple: &light_purple "#828dd1"

general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: False

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: true

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: true

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "2px"

  # Gap between windows and the screen edge.
  outer_gap: "2px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: *light_purple

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  height: "30px"
  position: "Top"
  opacity: 1.0
  background: *crust
  foreground: *light_purple
  font_family: "JetBrainsMono Nerd Font Mono"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: *light_purple
      focused_workspace_foreground: *crust
      displayed_workspace_background: *surface0
      default_workspace_background: "transparent"
      margin: "0 2px"
    - type: "cpu"
      label: "CPU"
      margin: "0 0 0 2px"
      background: *peach
      foreground: "#000000"
      padding: "0 10px"
      refresh_interval_ms: 100000
    - type: "cpu"
      label: "{percent_usage}%"
      margin: "0 2px"
      background: *surface0
      foreground: *peach
      padding: "0 10px"
      refresh_interval_ms: 1000
    - type: "gpu"
      label: "GPU"
      margin: "0 0 0 2px"
      background: *green
      foreground: "#000000"
      padding: "0 10px"
      refresh_interval_ms: 100000
    - type: "gpu"
      label: "{percent_usage}%"
      margin: "0 2px"
      background: *surface0
      foreground: *green
      padding: "0 10px"
      refresh_interval_ms: 1000
    - type: "memory"
      label: "MEM"
      margin: "0 0 0 2px"
      background: *yellow
      foreground: "#000000"
      padding: "0 10px"
      refresh_interval_ms: 100000
    - type: "memory"
      label: "{percent_usage}%"
      margin: "0 2px"
      background: *surface0
      foreground: *yellow
      padding: "0 10px"
      refresh_interval_ms: 1000
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
      margin: "0 4px"
    - type: "battery"
      margin: "0 0 0 2px"
      background: *yellow
      foreground: *surface0
      padding: "0 5px"
      label_draining: "🔋"
      label_power_saver: "⚠"
      label_charging: "🗲"
    - type: "battery"
      margin: "0 2px 0 0"
      foreground: *yellow
      background: *surface0
      padding: "0 10px"
      label_draining: "{battery_level}%"
      label_power_saver: "{battery_level}%"
      label_charging: "{battery_level}%"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: *light_purple
      foreground: "#000000"
      margin: "0 0 0 2px"
      padding: "0 8px"
    - type: "tiling direction"
      label_horizontal: "Horizontal"
      label_vertical: "Vertical"
      foreground: *lavender
      background: *surface0
      margin: "0 2px 0 0"
      padding: "0 8px"
    - type: "clock"
      margin: "0 0 0 2px"
      padding: "0 6px"
      background: *light_purple
      foreground: "#000000"
      time_formatting: "📅"
    - type: "clock"
      margin: "0 2px 0 0"
      padding: "0 6px"
      background: *dark_purple
      foreground: "#000000"
      time_formatting: "HH:mm  ddd dd.MM.yyyy (w)"

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Do not manage picture-in-picture windows for browsers. Note that the default is for
  # English; change `match_title` to the window's title if you use another language.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+J"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+I"]
  - command: "focus down"
    bindings: ["Alt+K"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Ctrl+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Ctrl+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Ctrl+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Ctrl+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+Left"
  - command: "resize width +2%"
    binding: "Alt+Right"
  - command: "resize height +2%"
    binding: "Alt+Up"
  - command: "resize height -2%"
    binding: "Alt+Down"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "toggle floating"
    binding: "Alt+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  - command: "exec wt"
    binding: "Alt+Ctrl+T"
  - command: "exec explorer"
    binding: "Alt+E"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
