window/bar:
  providers: [ 'self' ]
  width: '{{ self.args.MONITOR_WIDTH }}'
  height: '40'
  position_x: '{{ self.args.MONITOR_X }}'
  position_y: '{{ self.args.MONITOR_Y }}'
  z_order: 'normal'
  shown_in_taskbar: false
  resizable: false
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
    :root {
      --light_purple: #828dd1;
      --dark_purple: #6c77bb;
      --surface0: #3b414da0;
      --surface0_content: #3b414d;
      --crust: #2e3440b0;
      --yellow: #e5c890;
      --peach: #ef9f76;
      --blue: #8caaee;
    }
    * {
    font-weight: bold;
    }
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: var(--light_purple);
    font-family: JetBrainsMono Nerd Font Mono, ui-monospace, monospace;
    font-size: 12px;
    padding: 4px;
    border-bottom: 1px solid rgb(255 255 255 / 5%);;
    background: var(--crust);
    backdrop-filter: blur(10px) opacity(0.8);

  group/left:
    styles: |
      display: flex;
      align-items: center;

    template/glazewm_workspaces:
      styles: |
        display: flex;
        align-items: center;
        margin-right: 10px;

        .workspace {
          background: var(--surface0);
          margin-right: 4px;
          padding: 4px 8px;
          color: var(--light_purple);
          border: none;
          border-radius: 2px;
          cursor: pointer;
          display: flex;
            align-items: center;
            justify-content: center;

          &.displayed {
            background: var(--dark_purple);
          }

          &.focused,
          &:hover {
            background: var(--dark_purple);
            color: var(--surface0_content);
          }
        }
      providers: [ 'glazewm' ]
      events:
        - type: 'click'
          fn_path: 'script.js#focusWorkspace'
          selector: '.workspace'
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button
            class="workspace {{ workspace.hasFocus ? 'focused' : '' }} {{ workspace.isDisplayed ? 'displayed' : '' }}"
            id="{{ workspace.name }}"
          >
            {{ workspace.displayName ?? workspace.name }}
          </button>
        }
    template/memory:
      providers: [ 'memory' ]
      styles: |
        margin-right: 4px;
        .memory {
            display: flex;
            align-items: center;
            color: var(--peach);
        }
        .nf-fae-chip {
          border-radius: 2px 0 0 2px;
          height: 22px;
          margin: 0;
          background: var(--yellow);
          padding: 4px 8px;
          color: #000000;
        }
        .memory-percentage {
          display: flex;
          align-items: center;
          color: var(--yellow);
          height: 22px;
          background: var(--surface0);
          border-radius: 0 2px 2px 0;
          padding: 4px 8px;
        }
      template: |
        <div class="memory">
          <i class="nf nf-fae-chip"></i>
          <span class="memory-percentage">
            {{ Math.round(memory.usage) }}%
          </span>
        </div>

    template/cpu:
      providers: [ 'cpu' ]
      styles: |
        .cpu {
            display: flex;
            align-items: center;
            color: var(--peach);
        }
        .nf-oct-cpu {
          border-radius: 2px 0 0 2px;
          height: 22px;
          margin: 0;
          background: var(--peach);
          padding: 4px 8px;
          color: #000000;
          background: var(--peach);
        }
        .cpu-percentage {
          display: flex;
          align-items: center;
          color: var(--peach);
          height: 22px;
          background: var(--surface0);
          border-radius: 0 2px 2px 0;
          padding: 4px 8px;
        }
      template: |
        <div class="cpu">
          <i class="nf nf-oct-cpu"></i>
        <span class="cpu-percentage">
          {{ Math.round(cpu.usage) }}%
        </span>
        </div>


  group/center:
    styles: |
      justify-self: center;

    template/clock:
      providers: [ 'date' ]
      template: |
        {{ date.toFormat(date.now, 'EEE, d. MMM yyyy, t') }}

  group/right:
    styles: |
      justify-self: end;
      display: flex;

      .template {
        margin-left: 10px;
      }

    template/glazewm_other:
      providers: [ 'glazewm' ]
      styles: |
        .tiling-direction {
          display: flex;
          align-items: center;
          justify-content: center;
          background: var(--light_purple);
          color: #000000;
          border-radius: 2px;
          height: 22px;
          width: 22px;
          margin: 0;
          aspect-ratio: 1;
        }

      template: |
        @if (glazewm.tilingDirection === 'horizontal') {
          <i class="tiling-direction nf nf-md-swap_horizontal"></i>
        } @else {
          <i class="tiling-direction nf nf-md-swap_vertical"></i>
        }

    template/network:
      providers: [ 'network', 'util' ]
      styles: |
        .network {
            display: flex;
            align-items: center;
        }
        .network-icon {
          border-radius: 2px 0 0 2px;
          height: 22px;
          margin: 0;
          background: var(--blue);
          color: #000000;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 4px 4px 4px 6px;
        }
        .network-icon i {
          color: #000000;
        }
        .network-icon .wifi {
          padding-right: 4px;
          color: #000000;
        }
        .network-speed {
          display: flex;
          align-items: center;
          color: var(--blue);
          height: 22px;
          background: var(--surface0);
          border-radius: 0 2px 2px 0;
          padding: 4px 8px;
        }
      template: |
        <div class="network">
          <span class="network-icon">
            @if (network.defaultInterface?.type === 'ethernet') {
              <i class="nf nf-md-ethernet"></i>
            } @else if (network.defaultInterface?.type === 'wifi') {
              @if (network.defaultGateway?.signalStrength >= 80) {<i class="nf nf-md-wifi_strength_4 wifi"></i>}
              @else if (network.defaultGateway?.signalStrength >= 65) {<i class="nf nf-md-wifi_strength_3 wifi"></i>}
              @else if (network.defaultGateway?.signalStrength >= 40) {<i class="nf nf-md-wifi_strength_2 wifi"></i>}
              @else if (network.defaultGateway?.signalStrength >= 25) {<i class="nf nf-md-wifi_strength_1 wifi"></i>}
              @else {<i class="nf nf-md-wifi_strength_outline"></i>}
              {{ network.defaultGateway?.ssid }}
            } @else {
              <i class="nf nf-md-wifi_strength_off_outline"></i>
            }
          </span>
          <span class="network-speed">
           {{ util.convertBytes(network.traffic.received, 0, 'si_bytes') }} | {{ util.convertBytes(network.traffic.transmitted, 0, 'si_bytes') }}
          </span>
        </div>
    template/battery:
      providers: [ 'battery' ]
      styles: |
        .battery {
            display: flex;
            align-items: center;
        }
        .battery-icon {
          border-radius: 2px 0 0 2px;
          height: 22px;
          margin: 0;
          background: var(--yellow);
          padding: 4px 8px;
          color: #000000;
        }
        .battery-percentage {
          display: flex;
          align-items: center;
          color: var(--yellow);
          height: 22px;
          background: var(--surface0);
          border-radius: 0 2px 2px 0;
          padding: 4px 8px;
        }

      template: |
        <div class="battery">
          <span class="battery-icon">
            @if (battery.isCharging) {<i class="nf nf-md-power_plug charging-icon"></i>}
            @else if (battery.chargePercent > 90) {<i class="nf nf-fa-battery_4"></i>}
            @else if (battery.chargePercent > 70) {<i class="nf nf-fa-battery_3"></i>}
            @else if (battery.chargePercent > 40) {<i class="nf nf-fa-battery_2"></i>}
            @else if (battery.chargePercent > 20) {<i class="nf nf-fa-battery_1"></i>}
            @else {<i class="nf nf-fa-battery_0"></i>}
          </span>
          <span class="battery-percentage">
            {{ Math.round(battery.chargePercent) }}%
          </span>
        </div>
#    template/date:
#      providers: [ 'date' ]
#      styles: |
#        .calendar {
#            display: flex;
#            align-items: center;
#            color: #000000;
#        }
#        .nf-md-calendar {
#          border-radius: 2px 0 0 2px;
#          height: 22px;
#          margin: 0;
#          background: var(--light_purple);
#          padding: 4px 8px;
#          color: #000000;
#        }
#        .date {
#          display: flex;
#          align-items: center;
#          color: #000000;
#          height: 22px;
#          background: var(--dark_purple);
#          border-radius: 0 2px 2px 0;
#          padding: 4px 8px;
#        }
#      template: |
#        <div class="calendar">
#          <i class="nf nf-md-calendar"></i>
#        <span class="date">
#          {{ date.toFormat(date.now, 'HH:mm EEE DD.MM.yyyy') }}
#        </span>
#        </div>

