global:
  enable_devtools: true

window/bar:
  providers: ["self"]
  width: "{{ self.args.MONITOR_WIDTH }}"
  height: "60" #This one is a bit funky, if you are using scaling, adjust accordingly
  position_x: "{{ self.args.MONITOR_X }}"
  position_y: "{{ self.args.MONITOR_Y }}"
  z_order: "always_on_bottom"
  show_in_taskbar: true
  resizable: false
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
    @import "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css";
    @import "https://www.nerdfonts.com/assets/css/webfont.css";

    :root {
      --rp-base: #191724;
      --rp-base-alpha-bg: #191724dd;
      --rp-surface: #1f1d2e;
      --rp-overlay: #26233a;
      --rp-muted: #6e6a86;
      --rp-subtle: #908caa;
      --rp-text: #e0def4;
      --rp-love: #eb6f92;
      --rp-gold: #f6c177;
      --rp-rose: #ebbcba;
      --rp-pine: #31748f;
      --rp-foam: #9ccfd8;
      --rp-iris: #c4a7e7;
      --rp-highlight-low: #21202e;
      --rp-highlight-med: #403d52;
      --rp-highlight-high: #524f67;

      --rp-moon-base: #232136;
      --rp-moon-base-alpha-bg: #232136dd;
      --rp-moon-surface: #2a273f;
      --rp-moon-overlay: #393552;
      --rp-moon-muted: #6e6a86;
      --rp-moon-subtle: #908caa;
      --rp-moon-text: #e0def4;
      --rp-moon-love: #eb6f92;
      --rp-moon-gold: #f6c177;
      --rp-moon-rose: #ea9a97;
      --rp-moon-pine: #3e8fb0;
      --rp-moon-foam: #9ccfd8;
      --rp-moon-iris: #c4a7e7;
      --rp-moon-highlight-low: #2a283e;
      --rp-moon-highlight-med: #44415a;
      --rp-moon-highlight-high: #56526e;

      --rp-dawn-base: #faf4ed;
      --rp-dawn-base-alpha-bg: #faf4eddd
      --rp-dawn-surface: #fffaf3;
      --rp-dawn-overlay: #f2e9e1;
      --rp-dawn-muted: #9893a5;
      --rp-dawn-subtle: #797593;
      --rp-dawn-text: #575279;
      --rp-dawn-love: #b4637a;
      --rp-dawn-gold: #ea9d34;
      --rp-dawn-rose: #d7827e;
      --rp-dawn-pine: #286983;
      --rp-dawn-foam: #56949f;
      --rp-dawn-iris: #907aa9;
      --rp-dawn-highlight-low: #f4ede8;
      --rp-dawn-highlight-med: #dfdad9;
      --rp-dawn-highlight-high: #cecacd;

      --text: var(--rp-text);
      --bg: var(--rp-base-alpha-bg);
      --border: var(--rp-base);
      --icon: var(--rp-love);
      --memory: var(--rp-gold);
      --cpu: var(--rp-rose);
      --cpu-high-usage: var(--rp-love);
      --battery-good: var(--rp-foam);
      --battery-mid: var(--rp-gold);
      --battery-low: var(--rp-love);
      --ws-1: var(--rp-love);
      --ws-2: var(--rp-gold);
      --ws-3: var(--rp-rose);
      --ws-4: var(--rp-pine);
      --ws-5: var(--rp-foam);
      --ws-6: var(--rp-iris);
      --weather: var(--rp-foam);
    }

    @keyframes flash {
        from { opacity: 1.0; }
        50% { opacity: 0.5; }
        to { opacity: 1.0; }
    }

  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 40px;
    margin: 5px 10px;
    color: var(--text);
    font-family: "SF Mono", ui-monospace, monospace;
    font-size: 16px;
    font-weight: 600;

  group/left:
    styles: |
      display: flex;
      align-items: center;
      justify-content: space-between;
      background: var(--bg);
      border: 1px solid var(--border);
      border-radius: 9999px;
      height: 40px; 
      width: fit-content;

      .template {
        margin: 4px;
        display: flex;
        align-items: center;

        div {
          display: flex;
          align-items: center;
        }
      }

      #memory, #cpu, #battery {
        background: color-mix(in srgb, currentColor 10%, transparent);
        border-radius: 9999px;
        padding: 6px;
        i {
          font-size: 20px;
          margin-right: 7px;
        }
      }

    template/rose-pine:
      providers: [ 'glazewm' ]
      styles: |
        i {
          color: var(--icon);
          background: color-mix(in srgb, currentColor 10%, transparent);
          padding: 6px;
          border-radius: 9999px
        }
        
        .vertical {
          rotate: 90deg;
        }
      template: |
        <i class="nf nf-md-flower_tulip {{ glazewm.tilingDirection === 'vertical' ? '' : 'vertical'}}"></i>

    template/memory:
      providers: ["memory"]
      styles: |
        color: var(--memory);
      template: |
        <i class="ti ti-database"></i>
        {{ (memory.usedMemory / 1000000000).toFixed(2) }} GiB

    template/cpu:
      providers: ["cpu"]
      styles: |
        color: var(--cpu);

        .high-usage {
          color: var(--cpu-high-usage);
          animation: flash 0.5s infinite;
        }
      template: |
        <div class={{cpu.usage > 85 ? "high-usage" : ""}}>
          <i class="ti ti-cpu"></i>
          <span>{{ Math.round(cpu.usage) }}%</span>
        </div>

    template/battery:
      providers: ["battery"]
      styles: |
        .critical {
          color: var(--battery-low);
          animation: flash 1s infinite;
        }

        .low {
          color: var(--battery-low)
        }

        .mid {
          color: var(--battery-mid)
        }

        .good {
          color: var(--battery-good);
        }
      template: |
        <div class="
            @switch (true) {
              @case (battery.chargePercent > 75) { good }
              @case (battery.chargePercent > 50) { mid }
              @case (battery.chargePercent > 25) { low }
              @default { critical }
            }
          ">
         @if (battery.isCharging) {<i class="ti ti-battery-charging"></i>}
            @else if (battery.chargePercent > 90) {<i class="ti ti-battery-4"></i>}
            @else if (battery.chargePercent > 70) {<i class="ti ti-battery-3"></i>}
            @else if (battery.chargePercent > 40) {<i class="ti ti-battery-2"></i>}
            @else if (battery.chargePercent > 20) {<i class="ti ti-battery-1"></i>}
            @else {<i class="ti ti-battery-exclamation">}
            {{ Math.round(battery.chargePercent) }}%
        </div>

  group/center:
    styles: |
      justify-self: center;

    template/glazewm:
      styles: |
        height: 40px;
        display: flex;
        align-items: center;
        background: var(--bg);
        border: 1px solid var(--border);
        border-radius: 9999px;
        font-weight: 1000;

        .workspace {
          border: none;
          display: flex;
          align-items: center;
          justify-content: center;
          background: transparent;
        }
        
        .workspace span  {
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 2px;
          width: 22px;
          height: 22px;
          border-radius: 50%;
          border: 3px solid;
          font-weight: 1000;
        }
        
        .workspace.notInFocus span {
          background: var(--bg);
        }
        
        .workspace.focused span {
          color: var(--rp-base);
        }

        .workspace-1 span {
          color: var(--ws-1);
          border-color: var(--rp-love);
          background: var(--rp-love);
        }

        .workspace-2 span {
          color: var(--ws-2);
          border-color: var(--rp-gold);
          background: var(--rp-gold);
        }

        .workspace-3 span {
          color: var(--ws-3);
          border-color: var(--rp-rose);
          background: var(--rp-rose);
        }

        .workspace-4 span {
          color: var(--ws-4);
          border-color: var(--rp-pine);
          background: var(--rp-pine);
        }

        .workspace-5 span {
          color: var(--ws-5);
          border-color: var(--rp-foam);
          background: var(--rp-foam);
        }

        .workspace-6 span {
          color: var(--ws-6);
          border-color: var(--rp-iris);
          background: var(--rp-iris);
        }

      providers: ["glazewm"]
      events:
        - type: "click"
          fn_path: "script.js#focusWorkspace"
          selector: ".workspace"
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button class="workspace {{ workspace.hasFocus ? 'focused' : 'notInFocus' }} workspace-{{ workspace.name }}" id="{{ workspace.name }}">
            <span>{{ workspace.displayName ?? workspace.name }}</span>
          </button>
        }

  group/right:
    styles: |
      justify-self: end;
      height: 40px;
      display: flex;
      align-items: center;
      background: var(--bg);
      border: 1px solid var(--border);
      border-radius: 9999px;

      .template {
        margin: 4px;
        display: flex;
        align-items: center;
      }

      #network {
        background: color-mix(in srgb, currentColor 10%, transparent);
        border-radius: 9999px;
        padding: 6px;
        i {
          margin-right: 7px;
        }
      }

    template/network:
      providers: ["network", "util"]
      styles: |
        margin: 10px;
        i {
          font-size: 20px;
        }
        color: var(--weather);
      template: |
        @if (network.defaultInterface?.type === 'ethernet' || network.interfaces.length !== 0 && network.interfaces[0].type == 'ethernet') {
              <i class="ti ti-plug"></i>
            } @else if (network.defaultInterface?.type === 'wifi' || network.interfaces.length !== 0 && network.interfaces[0].type == 'wifi') {
              @if (network.defaultGateway?.signalStrength >= 80) {<i class="ti ti-antenna-bars-5 wifi"></i>}
              @else if (network.defaultGateway?.signalStrength >= 65) {<i class="ti ti-antenna-bars-4 wifi"></i>}
              @else if (network.defaultGateway?.signalStrength >= 40) {<i class="ti ti-antenna-bars-3 wifi"></i>}
              @else if (network.defaultGateway?.signalStrength >= 25) {<i class="ti ti-antenna-bars-2 wifi"></i>}
              @else {<i class="ti ti-antenna-bars-1 wifi"></i>}
              {{ network.defaultGateway?.ssid }}
            } @else {
              <i class="ti ti-world-off"></i>
            }
        {{util.convertBytes(network.traffic.received, 0, 'si_bytes') }} | {{ util.convertBytes(network.traffic.transmitted, 0, 'si_bytes') }}

    template/separator:
      styles: |
      template: |
        <i class="nf nf-oct-dot_fill"></>

    template/clock:
      providers: ["date"]
      styles: |
        padding-right: 6px;
      template: |
        {{ date.toFormat(date.now, 'EEE, d. MMM yyyy, t:s') }}